/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as IndexRouteImport } from './pages/index'
import { Route as DevPrototypeExampleIndexRouteImport } from './pages/dev/prototype-example/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DevPrototypeExampleIndexRoute =
  DevPrototypeExampleIndexRouteImport.update({
    id: '/dev/prototype-example/',
    path: '/dev/prototype-example/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dev/prototype-example/': typeof DevPrototypeExampleIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dev/prototype-example': typeof DevPrototypeExampleIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dev/prototype-example/': typeof DevPrototypeExampleIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dev/prototype-example/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dev/prototype-example'
  id: '__root__' | '/' | '/dev/prototype-example/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DevPrototypeExampleIndexRoute: typeof DevPrototypeExampleIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/prototype-example/': {
      id: '/dev/prototype-example/'
      path: '/dev/prototype-example'
      fullPath: '/dev/prototype-example/'
      preLoaderRoute: typeof DevPrototypeExampleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DevPrototypeExampleIndexRoute: DevPrototypeExampleIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
